### ISSUE TITLE
Add prepare scripts for github development mode

### ISSUE THREAD

**Issue by Seolhun** [Seolhun/localize-components#103]
## Purpose

- for UnPublished version 

## Why

- Develop version for usage

## TODO List

- Add npm `prepare` script

## Describe alternatives you've considered

- None

## Additional context

- None

---

#### Documents
- [ ] @seolhun/localize-components-docs
- [ ] @seolhun/localize-components-examples

#### Components
- [ ] @seolhun/localize-components
- [ ] @seolhun/localize-components-atomic

#### Mono Components
- [ ] @seolhun/localize-components-button
- [ ] @seolhun/localize-components-form
- [ ] @seolhun/localize-components-modal
- [ ] @seolhun/localize-components-sidebar

#### Utils
- [ ] @seolhun/localize-components-hooks
- [ ] @seolhun/localize-components-styled-utils
- [ ] @seolhun/localize-components-utils-event

#### Types
- [ ] @seolhun/localize-components-styled-types
- [ ] @seolhun/localize-components-types

**Comment by Seolhun** [comment]
098d494699df85a0907685a5b1e9c814d69714eb
