### ISSUE TITLE
[Component] Fix Modal Component removing deprecated pakcage

### ISSUE THREAD

**Issue by Seolhun** [Seolhun/localize-components#67]
## Purpose

To enhanced Modal

## Why

Modal dom has error

## TODO List

1. Removed deprecated package
2. Add Theme
3. Change Background DOM and zIndex

#### Contents
- [x] docs
- [x] examples

#### Components
- [ ] localize-components
- [ ] localize-components-atomic

#### Atomic Components
- [ ] localize-components-button
- [ ] localize-components-chip
- [ ] localize-components-drawer
- [ ] localize-components-form
- [ ] localize-components-icons
- [x] localize-components-modal
- [ ] localize-components-table

#### Types
- [ ] localize-components-types
- [ ] localize-components-types-style

#### Utils
- [ ] localize-components-utils-event
- [ ] localize-components-utils-style
