### ISSUE TITLE
[Component] Add figure components

### ISSUE THREAD

**Issue by Seolhun** [Seolhun/localize-components#95]
## Purpose

Add Figure components 

## Why

We need container with localize-styled figure

## TODO List

1. Circle
2. ...

## What packages is changed?
- [ ] @seolhun/localize-components-docs
- [ ] @seolhun/localize-components-examples
- [ ] @seolhun/localize-components
- [x] @seolhun/localize-components-atomic
- [ ] @seolhun/localize-components-button
- [ ] @seolhun/localize-components-modal
- [ ] @seolhun/localize-components-form

- [ ] @seolhun/localize-components-types
- [ ] @seolhun/localize-components-styled-types
- [ ] @seolhun/localize-components-styled-utils
- [ ] @seolhun/localize-components-utils-event

**Comment by Seolhun** [comment]
I considered this components. This is not required now

**Comment by Seolhun** [comment]
Not required component
